name: Code coverage report

# no permissions by default
permissions: {}

on:
  pull_request:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        persist-credentials: false

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f  # v0.10.0

    - name: Run tests with coverage
      run: >
        pixi run --frozen --environment testcov test_cov
