name: test

# no permissions by default
permissions: {}

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        environment: [ test311, test312, test313, test314 ]
        os: [ ubuntu-latest ]
        include:
          - os: windows-latest
            environment: test314
          - os: macos-latest
            environment: test314
          - os: macos-15-intel
            environment: test314
      fail-fast: false
    permissions:
      actions: none

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347  # v0.10.1

      - name: Tests
        run: >
          pixi run --frozen --environment ${{ matrix.environment }} test
