name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        environment: [test310, test311, test312]
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.7.0
        with:
          pixi-version: v0.22.0
          cache: true
          # auth-host: prefix.dev
          # auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
#      - run: pixi run --environment test312 lint
      - run: pixi run --environment ${{ matrix.environment }} test
  lint:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.7.0
        with:
          pixi-version: v0.22.0
          cache: true
          # auth-host: prefix.dev
          # auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - run: pixi run --environment test310 lint



